### ISSUE TITLE
Mod throws error when trying to log into dedicated server

### ISSUE THREAD

**Issue by literallygoblin** [NitrinaxValheim/NoPortal#1]
When trying to log into a dedicated server with this mod installed, a "string mismatched " error pops up. I am pretty sure it is somehow related to Azu-Anticheat, but I have never seen the error with any other mod except this one. No matter how we try to install the mod (on server and clients, or only client, even only server) the same error pops up. Screenshot here: https://ibb.co/jgz3dXY. I thought I'd be able to figure out what was going on, but I am at my wit's end. I'm therefore reporting it here in the hopes that it can be adressed and this gem of a mod can be added to the server.

**Comment by literallygoblin** [comment]
I am also

**Comment by literallygoblin** [comment]
Here is the modlist that the server is running, plus this mod:

BepInExPack_Valheim by denikson

Jotunn by ValheimModding

Mountup by Oran1

SaddleStaminaControl by Detalhes

BeastsOfBurden by clevel

Better_Trader_Remake by OdinPlus

TripleBronze by KaceCottam

SimpleRecycling_Fixed by remmiz

AzuAntiCheat by Azumatt

ServerCharacters by Smoothbrain

ValheimPlus by ValheimPlus

TerrainReset by Nexus

Build_In_Dungeons by LottieVixen

**Comment by NitrinaxValheim** [comment]
Thanks for reporting this. I will have a look at it. For now, the mod is only for the client. Note: If ValheimPlus is installed, then you can turn off the portals with it and don't need this mod.

disablePortals=true

in ValheimPlus config

**Comment by literallygoblin** [comment]
Oh, I am fully aware of the disablePortals value, that's what we currently use. What we want this mod for is to remove the portals from the the build menus but keep the ability to spawn them in so we can have a few strategically scattered around the world. When we just disable all portals outright, they're still buildable but won't work, which just makes them useless clutter.

**Comment by NitrinaxValheim** [comment]
i have uploaded a debug version 0.0.20 at https://discord.gg/mPmPf8N5

**Comment by NitrinaxValheim** [comment]
Bug fixed. Closed.
